### PR TITLE
Swift

### PR DESCRIPTION
**Pull request by 4ndrewHarri5**
I have written the snap game in swift as an IOS Application.

### CODE REVIEW

**Comment by alectunbridge** [comment]
Just to let you know I've seen this, afraid I don't know any Swift but I'll attempt to comment on the structure of the code from an object-oriented perspective.  If you want a verdict on the Swift stuff you'll need to find someone in your organisation with more experience in that area 👍

**Comment by 4ndrewHarri5** [comment]
Hi Alec,

Cheers for taking a look!

I wrote it purely to see if I could replicate it in swift. There are a few
developers on my floor who develop in swift so I'll reach out to them.

Thanks,

Andrew

**Comment by mrmanc** [comment]
Hey Andrew. Just revisiting this and wondering whether we should leave this PR open?

**Comment by harvy2004** [comment]
Unfortunately xcode can only be used on macbooks. There have been some attempt to make then run on windows but still fiddly https://swift.org/blog/swift-on-windows/

**Comment by 4ndrewHarri5** [comment]
Yes it would only make sense to merge in if there were apprentices who are working with Swift at their company. Can be closed 👍

**Comment by mrmanc** [comment]
Okay then. Thanks for responding 😃 I think I’ll close the PR but leave the branch there in case it comes up in the future.

**Pull request closed without merging**
